@baseUrl = http://localhost:5104
@id = 1

GET {{baseUrl}}/list
Accept: application/json

###

POST {{baseUrl}}/new
Accept: application/json
Content-Type: application/json

{
  "name": "Testing Application",
  "executable": "C:\\Windows\\System32\\cmd.exe"
}

###

POST {{baseUrl}}/{{id}}/start
Accept: application/json

###

DELETE {{baseUrl}}/{{id}}/stop
Accept: application/json

###

DELETE {{baseUrl}}/{{id}}/delete
Accept: application/json
Content-Type: application/json

###

POST {{baseUrl}}/{{id}}/stdin
Accept: application/json
Content-Type: application/json

{
  "text": "whoami"
}

###
