@baseUrl = http://localhost:5104
@name = test_application_pwsh
@forceStop = true

# List all applications
GET {{baseUrl}}/list
Accept: application/json

###

# Create a new application
POST {{baseUrl}}/new
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "executable": "C:/Windows/System32/cmd.exe"
}

###

# Get the information for an application
GET {{baseUrl}}/{{name}}
Accept: application/json

###

# Start an application
POST {{baseUrl}}/{{name}}
Accept: application/json

###

# Stop an application
DELETE {{baseUrl}}/{{name}}?forceStop={{forceStop}}
Accept: application/json

###

# Delete an application
DELETE {{baseUrl}}/{{name}}/delete?forceStop={{forceStop}}
Accept: application/json

###

# Send text into the Standard Input of a the application
POST {{baseUrl}}/{{name}}/stdin
Accept: application/json
Content-Type: application/json

{
  "text": "echo Hi world!`ntest"
}

###

# Edit an application
PATCH {{baseUrl}}/{{name}}
Accept: application/json
Content-Type: application/json

{
  "executable": "C:/Program Files/PowerShell/7/pwsh.exe"
}

###

# Get the logs for an application
GET {{baseUrl}}/{{name}}/logs?lines=20&noStreaming=true
Accept: application/json

###

# Stop the daemon
DELETE {{baseUrl}}/daemon/stop
