@baseUrl = http://localhost:5104
@name = test_application
@forceStop = true

GET {{baseUrl}}/list
Accept: application/json

###

POST {{baseUrl}}/new
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "executable": "C:\\Program Files\\nodejs\\node.exe",
  "arguments": "-e \"for (var i = 0; i < 1_000_000_000_000; i++) {}\""
}

###

POST {{baseUrl}}/{{name}}/start
Accept: application/json

###

DELETE {{baseUrl}}/{{name}}/stop?forceStop={{forceStop}}
Accept: application/json

###

DELETE {{baseUrl}}/{{name}}/delete?forceStop={{forceStop}}
Accept: application/json

###

POST {{baseUrl}}/{{name}}/stdin
Accept: application/json
Content-Type: application/json

{
  "text": "node -e \"for (var i = 0; i < 1_000_000_000_000; i++) {}\""
}

###
