name: .NET

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
  publish:
    name: Publish for ${{ matrix.platform }}-${{ matrix.arch }} (${{ matrix.self-contained }})
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        # The runtime id will be composed based on parts of the .NET Known RIDs (https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#known-rids)
        arch: ["x64", "arm64"]
        platform: ["win", "linux"]
        self-contained: ["no-self-contained", "self-contained"]
    steps:
      - uses: actions/checkout@v4
      - name: Restore dependencies
        run: dotnet restore --runtime ${{ matrix.platform }}-${{ matrix.arch }}
      - name: Publish for ${{ matrix.platform }}-${{ matrix.arch }} (${{ matrix.self-contained }})
        run: dotnet publish Hexus --no-restore --runtime ${{ matrix.platform }}-${{ matrix.arch }} --${{ matrix.self-contained }}
      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hexus-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.self-contained }}
          path: artifacts/publish/Hexus/release_${{ matrix.platform }}-${{ matrix.arch }}/Hexus${{ matrix.platform == 'win' && '.exe' || '' }}
          if-no-files-found: error
